logging:
  file:
    path: /var/log/${spring.application.name}
  level:
    com.example: debug
    org.springframework: debug
    org.springframework.boot.autoconfigure: info

spring:
  application:
    name: demo
  h2:
    console:
      enabled: true
      #path: /h2-console</databasename>

  datasource:
    #url: jdbc:h2:file:~/h2-demo
    url: jdbc:h2:mem:h2-demo
    username: sa
    password: sa
    driverClassName: org.h2.Driver
    schema: classpath:schema.sql

sqlhelper:
  mybatis:
    instrumentor:
      name: mybatis
      cache-instrumented-sql: true
      subquery-paging-start-flag: "[PAGING_START]"
      subquery-paging-end-flag: "[PAGING_END]"
